package com.btireland.talos.ethernet.engine.repository;


import com.btireland.talos.ethernet.engine.domain.QbtdcQuote;

import java.time.LocalDateTime;
import java.util.List;

public interface QbtdcQuoteRepository extends JpaRsqlRepository<QbtdcQuote, Long> {
    /**
     * Standard query method. The implementation will be generated by Spring.
     * Have a look here for further info https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories
     *
     * @param quoteStatus quote item status
     * @param orderStatus qbtdc order status
     * @param maxDate end Date range
     * @return The {@link QbtdcQuote}
     */

    List<QbtdcQuote> findByStatusAndQbtdcOrderStatusAndChangedAtBefore(String quoteStatus, String orderStatus, LocalDateTime maxDate);

}
